# Generated by Django 5.0.6 on 2024-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(choices=[('Arquitectura', 'Arquitectura'), ('Administración', 'Administración'), ('Contabilidad y Finanzas', 'Contabilidad y Finanzas'), ('Economía', 'Economía'), ('Marketing', 'Marketing'), ('Negocios Internacionales', 'Negocios Internacionales'), ('Comunicación', 'Comunicación'), ('Derecho', 'Derecho'), ('Ingeniería Civil', 'Ingeniería Civil'), ('Ingeniería Industrial', 'Ingeniería Industrial'), ('Ingeniería de Sistemas', 'Ingeniería de Sistemas'), ('Psicología', 'Psicología')], max_length=25),
        ),
    ]
