# Generated by Django 5.0.6 on 2024-06-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuarios/default.jpg', upload_to='usuarios/', verbose_name='Imagen'),
        ),
    ]
