# Generated by Django 5.0.6 on 2024-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuarios/default-avatar.jpg', upload_to='usuarios/', verbose_name='Imagen'),
        ),
    ]
