# Generated by Django 5.0.6 on 2024-07-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='archivo',
        ),
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='seccion.seccion'),
        ),
    ]
