# Generated by Django 5.0.6 on 2024-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_rename_material_material_archivo_material_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
