# Generated by Django 5.0.6 on 2024-06-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_curso_options'),
        ('estudiante', '0002_alter_estudiante_options_alter_estudiante_carrera'),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('curso', 'estudiante')},
        ),
    ]
