# Generated by Django 5.0.6 on 2024-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.IntegerField(max_length=8, unique=True, verbose_name='Código'),
        ),
    ]
