# Generated by Django 5.0.6 on 2024-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_estudiante',
            field=models.BooleanField(default=False, verbose_name='Usuario estudiante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_profesor',
            field=models.BooleanField(default=False, verbose_name='Usuario profesor'),
        ),
    ]
