# Generated by Django 5.0.6 on 2024-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='Código'),
        ),
    ]
