# Generated by Django 5.0.6 on 2024-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
