# Generated by Django 5.0.6 on 2024-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0002_alter_seccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
