# Generated by Django 5.0.6 on 2024-07-17 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Negocios', 'Negocios'), ('Finanzas', 'Finanzas'), ('Contabilidad', 'Contabilidad'), ('Informática y Software', 'Informática y Software'), ('Productividad', 'Productividad'), ('Diseño', 'Diseño'), ('Marketing', 'Marketing'), ('Economía', 'Economía'), ('Administración', 'Administración'), ('Derecho', 'Derecho'), ('Gestión de Proyectos', 'Gestión de Proyectos')], max_length=100)),
                ('nivel', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Experto', 'Experto')], max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='profesor.profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
