# Generated by Django 5.0.6 on 2024-07-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_seccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
    ]
