# Generated by Django 5.0.6 on 2024-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_curso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
