# Generated by Django 5.0.6 on 2024-06-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
    ]
