# Generated by Django 5.0.6 on 2024-06-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
