# Generated by Django 5.0.6 on 2024-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_calificacion_curso_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='curso',
            name='calificacion_promedio',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
