# Generated by Django 5.0.6 on 2024-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_curso_estudiantes_alter_curso_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiantes',
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
