# Generated by Django 5.0.6 on 2024-06-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_remove_curso_estudiantes_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
