# Generated by Django 5.0.6 on 2024-07-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
        ('curso', '0002_alter_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias', to='curso.curso'),
        ),
    ]
