# Generated by Django 5.0.6 on 2024-07-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='tema',
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='enlace',
            field=models.URLField(help_text='Enlace de la reunión'),
        ),
    ]
